name: Run Gradle
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    
    - uses: actions/checkout@v3
    - run: ls -al

    - name: gradle init
      run: ./demo/gradlew init

    - name: gradle build
      run: ./demo/gradlew build
    - run: ls -al