name: Run Gradle
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x ./demo/gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: demo
    - run: ls -al ./demo/build/libs

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./demo/build/libs

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./
    - run: ls -l
    - run: echo $PWD