name: Our Steps
on: workflow_dispatch

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: original
        run: exit 1
      - name: backup
        if: ${{ failure() }}
        run: echo backup

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: ls -al; echo $PWD

  #   - uses: actions/setup-java@v3
  #     with:
  #       distribution: corretto
  #       java-version: 11

  #   - name: Grant execute permission for gradlew
  #     run: chmod +x ./demo/gradlew
    
  #   - name: Build with Gradle
  #     run: ./gradlew clean build
  #     working-directory: demo
  #   - run: ls -al ./demo/build/libs

  #   - name: zip artifact
  #     run: |
  #       cd ./demo/build/libs
  #       zip -r -q ../../../artifact.zip .

  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: build-artifact
  #       path: ./artifact.zip

  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: staging-test
  #   concurrency:
  #     group: staging-test
  #     cancel-in-progress: true
  #   env:
  #     USER_NAME: ubuntu

  #   steps:
  #   - name: download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: build-artifact

  #   - name: scp tasks
  #     uses: appleboy/scp-action@v0.1.4
  #     with:
  #       host: ${{ secrets.STAGING_HOST }}
  #       username: ${{ env.USER_NAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       source: artifact.zip
  #       target: /home/ubuntu

  #   - name: ssh tasks
  #     uses: appleboy/ssh-action@v0.1.10
  #     with:
  #       host: ${{ secrets.STAGING_HOST }}
  #       username: ${{ env.USER_NAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script: /home/ubuntu/test.sh

  #   - name: check other env secrets
  #     run: echo ${{ secrets.DEVELOP_HOST }}

  # deploy-develop:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: develop-test
  #   concurrency:
  #     group: develop-test
  #     cancel-in-progress: true
  #   env:
  #     USER_NAME: ubuntu

  #   steps:
  #   - name: download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: build-artifact

  #   - name: scp tasks
  #     uses: appleboy/scp-action@v0.1.4
  #     with:
  #       host: ${{ secrets.DEVELOP_HOST }}
  #       username: ${{ env.USER_NAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       source: artifact.zip
  #       target: /home/ubuntu

  #   - name: ssh tasks
  #     uses: appleboy/ssh-action@v0.1.10
  #     with:
  #       host: ${{ secrets.DEVELOP_HOST }}
  #       username: ${{ env.USER_NAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script: /home/ubuntu/test.sh
