name: cd test

on:
  workflow_call:

jobs:
  develop:
    runs-on: ubuntu-latest
    environment:
      name: s3-upload
      # url: 


    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - run: ls -l ./
    - name: secret key encrypt & bypass test
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }}
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'

    - uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - run: ls -l
    - run: aws s3 cp artifact.zip s3://gh-action-s3-test/path1/artifact.zip
