name: check gh action env variables

on:
  workflow_dispatch:

env:
  GLOBAL_VARIABLE_1: test
  GLOBAL_VARIABLE_2: test1

jobs:
  env_check1:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: local
    steps:
      - uses: actions/checkout@v3
      - run: env
  
  # env_check2:
  #   runs-on: ubuntu-latest