name: scp deploy

on:
  workflow_call:

jobs:
  develop:
    runs-on: ubuntu-latest
    environment:
      name: scp-deploy
    env:
      HOST: "ec2-54-180-128-3.ap-northeast-2.compute.amazonaws.com"
      USER_NAME: "ubuntu"

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-artifact


    - uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "artifact.zip"
        target: /home/ubuntu/
