name: check gh action env variables

on:
  workflow_dispatch:

env:
  VARIABLE_1: test1 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: cat gh_env_check.sh
      
      - run: chmod u+x gh_env_check.sh
      
      - run: ls
      
      - run: cat deploy.yml