name: scp deploy

on:
  # push:
  workflow_call:

jobs:
  develop:
    runs-on: ubuntu-latest

    env:
      HOST: "ec2-54-180-128-3.ap-northeast-2.compute.amazonaws.com"
      USER_NAME: "ubuntu"
    
    steps:
    - uses: appleboy/scp-action@v0.1.4s
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./demo/build/libs/*"
        target: /home/ubuntu/