name: check gh action env variables

on:
  workflow_dispatch:

env:
  VARIABLE_1: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: env
      
      - run: |
          cat gh_env_check.sh | sed -i "s/${{ '\${{ env.VARIABLE_1 }}' }}/test/g"
          cat gh_env_check.sh