name: check gh action env variables

on:
  workflow_dispatch:

env:
  VARIABLE_1: test
  VARIABLE_2: test1
  VARIABLE_3: test2
  VARIABLE_4: test3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: env

      - run: ls

      # - run: cat gh_env_check.sh

      # - run: cat gh_env_check.sh | sed "s/${{ '\${{ env.VARIABLE_1 }}' }}/test/g"
      - run: echo ${{ 'default_value' }}
      - run: echo ${{ test || 'default_value' }}