name: scp deploy

on:
  push:
  # workflow_call:

jobs:
  develop:
    runs-on: ubuntu-latest

    env:
      HOST: "ec2-54-180-128-3.ap-northeast-2.compute.amazonaws.com"
      USER_NAME: "ubuntu"
    
    steps:
    - run: echo $HOST; echo $USER_NAME
    - run: ssh -i ${{ secrets.SSH_KEY }} $USER_NAME/$HOST echo test