name: 쉘 스크립트 function 사용 확인
on: workflow_dispatch

jobs:
  shell_func_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
  
      - name: custom action test
        uses: ./actions/test
        with:
          VERSION: test
