name: test in gh action
on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "gh_repo: ${{ github.repository }}"
        echo "gh_repo_owner: ${{ github.repository_owner }}"