name: timeout test
on:
  workflow_dispatch

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    - name: sleep 59
      run: echo "sleep 59..."; sleep 59

    - name: Run when canceled
      if: ${{ cancelled() }}
      run: echo cancel


  
